spring.application.name=attendance-app

# Supabase/PostgreSQL Database Connection Settings
# プーラー用の接続文字列に変更
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.zgonhovfhhivbvfxlenc
spring.datasource.password=G5fkhsmkvq4ypca

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
